name: react-ts

services:
  front:
    env_file:
      - ../.env
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - "..:/workspace:cached"
    command: sleep infinity
